# Configuration File for CodeCov
codecov:
  require_ci_to_pass: no
  notify:
    require_ci_to_pass: no
    wait_for_ci: false
  ci:
    - jenkins.milvus.io:18080
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: off
      #      default:
      #  target: 77%
      #  threshold: 0% #Allow the coverage to drop by threshold%, and posting a success status.
    patch: off
      #      default:
      #  target: 80%   #target of patch diff
      #  threshold: 0%
      #  if_ci_failed: error #success, failure, error, ignore

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    statuses:
      - type: project
        target: 77%
        threshold: 0%
      - type: patch
        target: 80%
        threshold: 0%
        if_ci_failed: error #success, failure, error, ignore

  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: core
      paths: 
      - internal
      - pkg
      statuses:
        - type: project
          target: 77%
        - type: patch
          target: 80%
    - name: client
      paths: 
      - client
      statuses:
      - type: project
        target: 77%
      - type: patch
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches: # branch names that can post comment
    - master

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.md"
  - "docs/.*"
  - "**/*.pb.go"
  - "**/*.proto"
  - "internal/metastore/db/dbmodel/mocks/.*"
  - "**/mock_*.go"



