version: '3.5'

volumes:
  amd64-ubuntu-18.04-cache:

x-ccache: &ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  CCACHE_MAXSIZE: 2G
  CCACHE_DIR: /build/ccache

x-command: &cpp-command >
  /bin/bash -c "
    /milvus/ci/scripts/build.sh -l -u -c"

services:
  ubuntu-core:
    image: ${REPO}:${ARCH}-ubuntu-${UBUNTU}-core
    build:
      context: .
      dockerfile: ci/docker/ubuntu-${UBUNTU}-core.dockerfile
      cache_from:
        - ${REPO}:${ARCH}-ubuntu-${UBUNTU}-core
    shm_size: 2G
    environment:
      <<: *ccache
    volumes: &ubuntu-volumes
      - .:/milvus:delegated
      - ${ARCH}-ubuntu-${UBUNTU}-cache:/build:delegated
    command: *cpp-command
