---
- name: Create milvus-etcd, minio, pulsar #Milvus dependent
  hosts: dependencies
  become: yes
  become_user: root
  tags: docker
  roles:
    - deploy-etcd
    - deploy-minio
    - deploy-pulsar

- name: Create milvus nodes #Deploy all 3 nodes on the same host can be benefitial from I/O optimized disk, and it's easier to have additional host running a set of milvus nodes.
  hosts: nodes
  become: yes
  become_user: root
  tags: docker
  roles:
    - deploy-datanode
    - deploy-indexnode
    - deploy-querynode

- name: Create milvus coords #Deploy all Coordinators and Proxy on the same host will reduce time to traffic on network.
  hosts: coords
  become: yes
  become_user: root
  tags: docker
  roles:
    - deploy-rootcoord
    - deploy-indexcoord
    - deploy-datacoord
    - deploy-querycoord
    - deploy-proxy




  



