apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-db-disk
  namespace: milvus-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-mysql-disk
  namespace: milvus-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-proxy-log
  namespace: milvus-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
