kind: Service
apiVersion: v1
metadata:
  name: milvus-ro-servers
  namespace: milvus-demo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: milvus
    tier: ro-servers
  ports:
    - protocol: TCP
      port: 19530
      targetPort: 19530
      name: engine
    - protocol: TCP
      port: 19121
      targetPort: 19121
      name: web
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: milvus-ro-servers
  namespace: milvus-demo
spec:
  selector:
    matchLabels:
      app: milvus
      tier: ro-servers
  template:
    metadata:
      labels:
        app: milvus
        tier: ro-servers
    spec:
      containers:
        - image: milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 19530
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          name: milvus-ro-server
          ports:
            - containerPort: 19530
              name: engine
              protocol: TCP
            - containerPort: 19121
              name: web
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 19530
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: milvus-db-disk
              mountPath: /var/milvus/data
              subPath: data
            - name: milvus-db-disk
              mountPath: /var/milvus/logs
              subPath: logs
            - name: milvus-ro-configmap
              mountPath: /var/lib/milvus/conf/server_config.yaml
              subPath: config.yml
      volumes:
      - name: milvus-ro-configmap
        configMap:
            name: milvus-ro-configmap
      - name: milvus-db-disk
        persistentVolumeClaim:
            claimName: milvus-db-disk


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-ro-servers
  namespace: milvus-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: milvus
      tier: ro-servers
  template:
    metadata:
      labels:
        app: milvus
        tier: ro-servers
    spec:
      terminationGracePeriodSeconds: 11
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: tier
                      operator: In
                      values:
                        - ro-servers
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - image: milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 19530
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          name: milvus-ro-server
          ports:
            - containerPort: 19530
              name: engine
              protocol: TCP
            - containerPort: 19121
              name: web
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 19530
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: milvus-db-disk
              mountPath: /var/milvus/data
              subPath: data
            - name: milvus-db-disk
              mountPath: /var/milvus/logs
              subPath: logs
            - name: milvus-ro-configmap
              mountPath: /var/lib/milvus/conf/milvus.yaml
              subPath: config.yml
      volumes:
      - name: milvus-ro-configmap
        configMap:
            name: milvus-ro-configmap
      - name: milvus-db-disk
        persistentVolumeClaim:
            claimName: milvus-db-disk
